DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS foot_traffic cascade;

CREATE TABLE users (
    id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT,
    password        TEXT
);

CREATE TABLE foot_traffic (
    id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER     REFERENCES users,
    counter         INTEGER,
    date            DATE,
    hour            INTEGER
);